# Generated by Django 6.0.1 on 2026-01-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text="Member's first name", max_length=255)),
                ('lastname', models.CharField(help_text="Member's last name", max_length=255)),
                ('email', models.EmailField(help_text="Member's email address", max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text="Member's phone number", max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True, help_text='Date member joined')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
