# Generated by Django 6.0.1 on 2026-01-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Team description')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Member biography')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=20)),
                ('favorite_surface', models.CharField(blank=True, choices=[('clay', 'Clay'), ('grass', 'Grass'), ('hard', 'Hard Court')], max_length=20)),
                ('member', models.OneToOneField(help_text='Member this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this member belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.team'),
        ),
    ]
