# Generated by Django 6.0.1 on 2026-01-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_team_profile_member_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tournament name', max_length=255)),
                ('location', models.CharField(help_text='Tournament location', max_length=255)),
                ('start_date', models.DateField(help_text='Tournament start date')),
                ('end_date', models.DateField(help_text='Tournament end date')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='tournaments',
            field=models.ManyToManyField(blank=True, help_text='Tournaments this member is participating in', related_name='members', to='members.tournament'),
        ),
    ]
