# Generated by Django 6.0.1 on 2026-01-20 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_tournament_member_tournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Match date')),
                ('location', models.CharField(blank=True, help_text='Match location', max_length=255)),
                ('player1_score', models.IntegerField(blank=True, help_text='Player 1 score', null=True)),
                ('player2_score', models.IntegerField(blank=True, help_text='Player 2 score', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Has match been completed?')),
                ('player1', models.ForeignKey(help_text='First player', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='members.member')),
                ('player2', models.ForeignKey(help_text='Second player', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='members.member')),
                ('winner', models.ForeignKey(blank=True, help_text='Match winner (optional until match is complete)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='members.member')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-date'],
            },
        ),
    ]
